import type { Metadata } from 'next'
// eslint-disable-next-line camelcase
import { Bai_Jamjuree } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
const bai = Bai_Jamjuree({ weight: ['400'], subsets: ['thai'] })

export const metadata: Metadata = {
  title: 'Financial Pannel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body
        className={`${bai.className} m-6 bg-blue-chill-950 flex justify-center text-base tracking-wider`}
      >
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}
